import '../styles/globals.css'
import Head from 'next/head';
import { Grid } from '@mui/material';
import styles from '../styles/Home.module.css';
import { VPEContextProvider } from "../context/VPEContext";
function MyApp({ Component, pageProps }) {
  return (
    <VPEContextProvider>
      <Grid container className={styles.container} justifyContent="center">
        <Grid item xs={11}>
          <Head>
            <title>Physical Examination Flow</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        
          <main className={styles.main}>
            <Component {...pageProps} />
          </main>
        </Grid>
      </Grid>
      
    </VPEContextProvider> 
  );
}

export default MyApp
